### ISSUE TITLE
Where do i find the token

### ISSUE THREAD

**Issue by pax47** [imbaggaarm/free4talk#1]
please can you briefly tell me where to find the room's token?

**Comment by imbaggaarm** [comment]
You just need to inspect the source code and check the Network tab as the screenshot attached bellow.
<img width="1680" alt="Screen Shot 2020-12-08 at 11 43 24 AM" src="https://user-images.githubusercontent.com/22892656/101440970-97148680-394a-11eb-8bc1-2d71183536c1.png">

**Comment by pax47** [comment]
thanks

**Comment by shindeaditya685** [comment]
i followed the steps but owner of website has removed that field from response. so that we are not able to get the room token.
